#! /usr/bin/env bash
# Set alias for nvim <- vim
read -p "Remove existing nvim / tmux config files? (y/n) " USER_IN
case $USER_IN in
  [Yy]* ) echo "Removing existing files"
          rm -rf ~/.config/nvim/
          rm -rf ~/.config/tmux;;
  [Nn]* ) ;;
  * ) ;;
esac

unzip nvim.zip -d ~/.config/
unzip tmux.zip -d ~/.config/

YUM=$(which yum)
APT=$(which apt-get)
DNF=$(which dnf)

packages="make cmake tmux xsel"
if [[ ! -z $YUM ]]; then
  sudo yum install $packages -y
elif [[ ! -z $APT ]]; then
  sudo apt-get install $packages -y  
elif [[ ! -z $DNF ]]; then 
  sudo dnf install $packages -y
else
  echo "Can't determine package manager to install tmux / neovim"
  exit 0
fi

read -p "(Re)Build nvim? (y/n) " USER_IN
case $USER_IN in
  [Yy]* ) INITIAL=$(git config --global http.sslverify)

          git config --global http.sslverify false
          git clone https://github.com/neovim/neovim.git
          git -C neovim checkout v0.9.5
          git config --global http.sslverify ${INITIAL}

          cd neovim
          sudo rm -r .build
          sudo make install
          cd ..;;
  [Nn]* ) ;;
  * ) ;;
esac

mkdir ~/.local/share/fonts
cp SauceCodeProNerdFontMono-Regular.ttf ~/.local/share/fonts/

# Set alias for nvim <- vim
read -p "Alias vim as nvim? (y/n) " USER_IN
case $USER_IN in
  [Yy]* ) echo "Removing existing alias"
          unalias vim 2>/dev/null
          echo "Creating new alias"
          echo "alias vim=\"nvim\"" >> ~/.bashrc;;
  [Nn]* ) ;;
  * ) ;;
esac
